import supplied from "./client-content.json";

/**
 * The people, from the client's Drive delivery of 2026-10-08 (bios and
 * headshots). Generated by scripts/build-client-content.py.
 *
 * `photo` is null where no headshot was supplied (Lisa Hamilton): her row has
 * no image slot at all — no initials plate, no placeholder (verdict V82). Doug Vincent's
 * bio is held — its securities disclosure is cut off mid-sentence in the
 * source — so he is absent until the complete text arrives (build/CLIENT-GAPS.md).
 */
export type TeamMember = {
  readonly slug: string;
  readonly name: string;
  readonly role: string;
  readonly summary: string;
  /** The founder's page predates the team pages and keeps its own route. */
  readonly href: string;
  readonly photo: string | null;
  /** A head-and-shoulders crop for the roster, where the photograph is a wide office shot. */
  readonly thumb: string | null;
};

export const TEAM: readonly TeamMember[] = supplied.team;

export function teamMember(slug: string): TeamMember | undefined {
  return TEAM.find((member) => member.slug === slug);
}

/** Members with their own /about/team/<slug> page, for static generation. */
export function teamRoutes(): readonly TeamMember[] {
  return TEAM.filter((member) => member.href === `/about/team/${member.slug}`);
}
